# Site wide configuration

title: Ömer Yaylaaltı
locale: en_US
description: Bilgisayar Mühendisi
logo: profile.png
search: true
url: http://omeryaylaalti.github.io/

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Ömer Yaylaaltı
  avatar: profile.png
  email: omer.yaylaalti1@gmail.com
  disqus-shortname:
  twitter: omer_y34
  facebook: #username
  github: omeryaylaalti
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: ömer-yaylaaltı-6a3b8386
  instagram: omeryaylaalti
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
